spring.application.name=linktrackr
spring.datasource.url=jdbc:postgresql://localhost:5432/linktrackr
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=drop-and-create
linktrackr.default.url=http://localhost:8080/